/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DevicesRouteRouteImport } from './routes/devices/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPersonasRouteImport } from './routes/admin/personas'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVoicesRouteImport } from './routes/admin/voices'
import { Route as DevicesIndexRouteImport } from './routes/devices/index'
import { Route as DevicesDeviceIdMeetRouteImport } from './routes/devices/$deviceId/meet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRouteRoute = DevicesRouteRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPersonasRoute = AdminPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVoicesRoute = AdminVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRouteRoute,
} as any)
const DevicesDeviceIdMeetRoute = DevicesDeviceIdMeetRouteImport.update({
  id: '/$deviceId/meet',
  path: '/$deviceId/meet',
  getParentRoute: () => DevicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/devices': typeof DevicesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin/': typeof AdminIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/$deviceId/meet': typeof DevicesDeviceIdMeetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin': typeof AdminIndexRoute
  '/devices': typeof DevicesIndexRoute
  '/devices/$deviceId/meet': typeof DevicesDeviceIdMeetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/devices': typeof DevicesRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/personas': typeof AdminPersonasRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin/': typeof AdminIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/devices/$deviceId/meet': typeof DevicesDeviceIdMeetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/devices'
    | '/login'
    | '/admin/personas'
    | '/admin/users'
    | '/admin/voices'
    | '/admin/'
    | '/devices/'
    | '/devices/$deviceId/meet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/personas'
    | '/admin/users'
    | '/admin/voices'
    | '/admin'
    | '/devices'
    | '/devices/$deviceId/meet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/devices'
    | '/login'
    | '/admin/personas'
    | '/admin/users'
    | '/admin/voices'
    | '/admin/'
    | '/devices/'
    | '/devices/$deviceId/meet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DevicesRouteRoute: typeof DevicesRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/personas': {
      id: '/admin/personas'
      path: '/personas'
      fullPath: '/admin/personas'
      preLoaderRoute: typeof AdminPersonasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/voices': {
      id: '/admin/voices'
      path: '/voices'
      fullPath: '/admin/voices'
      preLoaderRoute: typeof AdminVoicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
    '/devices/$deviceId/meet': {
      id: '/devices/$deviceId/meet'
      path: '/$deviceId/meet'
      fullPath: '/devices/$deviceId/meet'
      preLoaderRoute: typeof DevicesDeviceIdMeetRouteImport
      parentRoute: typeof DevicesRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPersonasRoute: typeof AdminPersonasRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoicesRoute: typeof AdminVoicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPersonasRoute: AdminPersonasRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoicesRoute: AdminVoicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DevicesRouteRouteChildren {
  DevicesIndexRoute: typeof DevicesIndexRoute
  DevicesDeviceIdMeetRoute: typeof DevicesDeviceIdMeetRoute
}

const DevicesRouteRouteChildren: DevicesRouteRouteChildren = {
  DevicesIndexRoute: DevicesIndexRoute,
  DevicesDeviceIdMeetRoute: DevicesDeviceIdMeetRoute,
}

const DevicesRouteRouteWithChildren = DevicesRouteRoute._addFileChildren(
  DevicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DevicesRouteRoute: DevicesRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
